---
title: "Indian Hills"
author: "DK"
date: "2026-10-03"
categories: [neighborhoods]
---

Three years after the marriage and two children later, we were looking for our first home.

Two houses were available, same price, close to each other, same school district with one significant difference.

One was facing a busy street and the other was in a neighborhood-only road.

We weren't sure since we were new to house hunting.

My mother said,

> "Look towards the future when your children are toddlers, would you want them to ride their tricycles near a busy road."

That sealed our decision to move into the Indian Hills area of the town.

------------------------------------------------------------------------

The lot south of the new house was empty and was kept that way by the neighbor across from us.

He wanted an unencumbered view of Utah Lake.

Often he would battle the weeds, especially dandelions on the .22 acre (9583 square feet) plot.

For our children and the neighbor's grandson, the empty lot was their playground that was larger than their imagination.

------------------------------------------------------------------------

It was at that house 2 more children joined the family.

As my mom predicted our children learned how to ride tricycles and bicycles on the driveway and on the road by the house.

Later on we learned that the neighbor across the street was at one time a high profile corporate lawyer that worked for what was then the largest corporation in the world.

We sold the house when the work assigned me to work overseas.

We had realized a sizeable return on investment but most of all because we listened to a more wise voice, we were able to raise the family in relative peace and quiet.
